import Image from "next/image";
import Link from "next/link";
import { PageShell } from "../site-shell";

const chapters = [
  { number:"01", title:"2000 — The Beginning", text:"Paris Passion Events was founded in Visakhapatnam in 2000. Early work across promotions, campaigns and events demanded resourcefulness, local understanding and hands-on responsibility from the first brief to the last operational detail.", image:"/images/institutional.webp", alt:"Representative early-stage professional event environment" },
  { number:"02", title:"Experience Expands", text:"Experience widened through roadshows, promotions, product launches, public programmes, entertainment and brand campaigns. Working across different locations and audiences developed the ability to adapt ideas to the field while maintaining consistency, coordination and purpose.", image:"/images/activation.webp", alt:"Representative brand activation and roadshow environment" },
  { number:"03", title:"Responsibility Grows", text:"The organisation’s role grew beyond individual execution tasks into broader responsibility for corporate events, conferences, exhibitions and institutional programmes. More stakeholders and more dependencies called for deeper planning, clearer communication and dependable on-ground leadership.", image:"/images/corporate.webp", alt:"Representative formal corporate event environment" },
  { number:"04", title:"Capability Expands", text:"As client requirements became more integrated, Paris Passion expanded into MICE, branding, PR, media, project coordination, administration, travel and hospitality. These are not isolated services; they are connected capabilities brought together according to each requirement.", image:"/images/mice.webp", alt:"Representative MICE and delegate hospitality environment" },
  { number:"05", title:"Today", text:"Today, Paris Passion is positioned as an experienced, selective and premium partner for corporate, government and institutional requirements. Selective means fewer engagements, closer involvement and deeper ownership—not distance from the client or the work.", image:"/images/production.webp", alt:"Representative contemporary production environment" },
];

export default function JourneyPage() {
  return <PageShell>
    <section className="page-hero journey-page-hero"><div><p className="eyebrow">Our journey</p><h1>Experience is built by taking <em>responsibility.</em></h1><p>More than two decades of learning what complex experiences require: clear thinking, strong relationships, practical coordination and ownership that lasts through delivery.</p></div><div className="journey-year"><strong>2000</strong><span>Visakhapatnam</span></div></section>
    <section className="journey-story paper-section">{chapters.map((chapter,index)=><article className={`journey-chapter ${index%2 ? "reverse" : ""}`} key={chapter.title}><div className="chapter-image"><Image src={chapter.image} alt={chapter.alt} width={1024} height={1024} sizes="48vw" /></div><div className="chapter-copy"><span>{chapter.number} / 05</span><h2>{chapter.title}</h2><p>{chapter.text}</p></div></article>)}</section>
    <section className="philosophy ink-section"><div><p className="eyebrow">Our philosophy</p><h2>Your Goal is <em>Our</em> Goal.</h2></div><div><p>It is a simple line, but it defines the relationship. We begin with the client’s objective, make the surrounding complexity visible, and take responsibility for coordinating the parts we are trusted to deliver.</p><p>The quality of an engagement is measured not only by what the audience sees, but by how responsibly the entire process is managed.</p></div></section>
    <section className="values paper-section"><div><p className="eyebrow">How we work</p><h2>Values that stay present in the work.</h2></div><ul>{["Integrity","Creativity","Commitment","Client Focus","Excellence","Relationships"].map((value,index)=><li key={value}><span>{String(index+1).padStart(2,"0")}</span><b>{value}</b></li>)}</ul></section>
    <section className="page-close ink-section"><p className="eyebrow">The next chapter</p><h2>Experienced. Selective. <em>Premium.</em></h2><p>For serious requirements that need more than suppliers—for clients looking for one experienced partner who can coordinate the larger picture.</p><Link className="button" href="/contact">Discuss Your Requirement</Link></section>
  </PageShell>;
}
